Issue 79- Theming and colors of Application
effektio/effektio pull request #101
Opened 2022-05-16 06:10 UTC by sachintha-s

#79
- Dark & light theme added
- Roboto text theme was added as the text theme for the entire app.
- For the light theme, some screens maybe need more styles than now. I think we can do that when the designer finishes the light theme.

2022-05-16 09:16 UTC, gnunicorn commented
> For the light theme, some screens maybe need more styles than now. I think we can do that when the designer finishes the light theme.

Yeah, light theme doesn't have priority at the moment. For the MVP, we won't even allow people to switch the themes yet...

2022-05-16 17:23 UTC, gnunicorn requested changes
how about using https://pub.dev/packages/themed or something like it?

2022-05-17 17:16 UTC, sachintha-s commented on app/lib/common/store/Colors.dart
> +  //light theme colors
Sure, I am trying to use that package.

2022-05-17 17:16 UTC, sachintha-s commented on app/lib/common/widget/FaqListItem.dart
> +                    : AppColors.lightFaqCardColor,
Noted. thanks

2022-05-18 11:18 UTC, gtalha07 approved these changes

2022-05-19 21:15 UTC, gnunicorn approved these changes

2022-05-19 21:15 UTC, merged