fix news bar alignment
effektio/effektio pull request #336
Opened 2022-11-04 13:02 UTC by gtalha07

### Description:
Fixed the like icon alignment.

2022-11-04 21:07 UTC, sachintha-s requested changes
Please tap on the like button and check it out. When it animates it goes to the edge of the device. I think the alignment should be improved when it is animated.

2022-11-11 11:17 UTC, gtalha07 commented
> Please tap on the like button and check it out. When it animates it goes to the edge of the device. I think the alignment should be improved when it is animated.

Will fix it.

2022-11-11 13:59 UTC, bitfriend commented on app/lib/widgets/NewsItem.dart
> +                  ? isDesktop
Yeah, desktop layout should be different somewhat from mobile desktop.

2022-11-11 13:59 UTC, bitfriend approved these changes
Looks good to me

2022-11-11 16:57 UTC, merged